### ISSUE TITLE
Suggestion: An example of OpenAI streaming will be very impressive.

### ISSUE THREAD

**Issue by MRYingLEE** [DerThorsten/xeus-javascript#6]
ChatGPT is still hot. 
An example of OpenAI (https://www.npmjs.com/package/openai) streaming will be very impressive.

**Comment by DerThorsten** [comment]
but this is a typescript package.
If you have a javascript package on jsdelivr you can probably just import it

**Comment by MRYingLEE** [comment]
import 'https://cdn.jsdelivr.net/npm/openai@4.20.1/+esm'

met the error:

Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://cdn.jsdelivr.net/npm/openai@4.20.1/+esm' failed to load.
    at afunc (eval at Module._make_async_from_code (https://jupyter-xeus.github.io/xeus-javascript/xeus/bin/xjavascript.js:8:1831), <anonymous>:4:9)
    at Module._call_user_code (https://jupyter-xeus.github.io/xeus-javascript/xeus/bin/xjavascript.js:8:3097)
    at __emval_call (https://jupyter-xeus.github.io/xeus-javascript/xeus/bin/xjavascript.js:8:167800)
    at https://jupyter-xeus.github.io/xeus-javascript/xeus/bin/xjavascript.wasm:wasm-function[5667]:0x2c6250
    at ret.<computed> [as dynCall_iiiii] (https://jupyter-xeus.github.io/xeus-javascript/xeus/bin/xjavascript.js:8:147198)
    at invoke_iiiii (https://jupyter-xeus.github.io/xeus-javascript/xeus/bin/xjavascript.js:8:3593512)
    at https://jupyter-xeus.github.io/xeus-javascript/xeus/bin/xjavascript.wasm:wasm-function[361]:0xd6fed
    at https://jupyter-xeus.github.io/xeus-javascript/xeus/bin/xjavascript.wasm:wasm-function[5678]:0x2c6e25
    at ret.<computed> [as dynCall_viiiiiiii] (https://jupyter-xeus.github.io/xeus-javascript/xeus/bin/xjavascript.js:8:147198)
    at invoke_viiiiiiii (https://jupyter-xeus.github.io/xeus-javascript/xeus/bin/xjavascript.js:8:3596228)

The reference code can be found at https://github.com/search?q=%22https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fopenai%404.2%22+language%3AHTML&type=code&l=HTML.

Please check.

**Comment by DerThorsten** [comment]
the  import statement `import 'https://cdn.jsdelivr.net/npm/openai@4.20.1/+esm'` is emulate via `importScripts` since the normal imort syntax **cannot** work since the user code / the code in the cells is run trough `eval` / `Function`.
See https://github.com/jupyter-xeus/xeus-javascript/issues/4


So you might need to experiment with `await import`

**Comment by DerThorsten** [comment]
This is working:

```JavaScript
const {default: openai} = await import('https://cdn.jsdelivr.net/npm/openai@4.26.0/+esm');
console.log(openai)
globalThis.openai = openai  // this is only needed because some bug/issue with scoping, will be fixed soon
```

**Comment by DerThorsten** [comment]
with the latest version you can do  (and may other import statement variants; see the demo notebook)
```js
import OpenAI  from "https://cdn.jsdelivr.net/npm/openai@4.26.0/+esm"
```

**Comment by DerThorsten** [comment]
closing this as the import is working
